algoritmo "semnome"
var
n1, n2, total1, total2, total3, total4: real
inicio
escreval ("Insira um valor:")
leia(n1)
escreval ("Insira um valor:")
leia(n2)

total1<-n1+n2
total2<-n1-n2
total3<-n1/n2
total4<-n1*n2

escreva("A soma dos valores é:")
escreval(total1)
escreva("A subtração dos valores é:")
escreval(total2)
escreva("A divisão dos valores é:")
escreval(total3)
escreva("A multiplicação dos valores é:")
escreval(total4)




fimalgoritmo
